steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-southeast2-docker.pkg.dev/jejakrempah-app/ml-jejakrempah/ml-jejakrempah-image:1.0.0"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-southeast2-docker.pkg.dev/jejakrempah-app/ml-jejakrempah/ml-jejakrempah-image:1.0.0"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "ml-jejakrempah"
      - "--image"
      - "asia-southeast2-docker.pkg.dev/jejakrempah-app/ml-jejakrempah/ml-jejakrempah-image:1.0.0"
      - "--region"
      - "asia-southeast2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--timeout"
      - "600s"

options:
  logging: CLOUD_LOGGING_ONLY
